version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    env_file: .env
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - hexabot-frontend
